src/Form/RegistrationType.php
<?php
/**
 * Created by PhpStorm.
 * User: skillup_student
 * Date: 17.04.18
 * Time: 20:58
 */

namespace App\Form;

use FOS\UserBundle\Form\Type\RegistrationFormType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\FormBuilderInterface;

class RegistrationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('acceptRules', CheckboxType::class);
    }

    public function getParent()
    {
        return RegistrationFormType::class;
    }
}

src/Controller/AboutController.php
<?php

namespace App\Controller;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class AboutController extends Controller
{
    /**
     * @Route("/about", name="about")
     */
    public function index()
    {
        return $this->render('about/index.html.twig', [
            'controller_name' => 'AboutController',
        ]);
    }
}

templates/about/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>{{ category.name }}</h1>

    <ul>
        {% if category.parent %}
            <li>
                <a href="{{ path('category_show', {id: category.parent.id}) }}">
                    Back
                </a>
            </li>
        {% endif %}

        {% for subcategory in category.subcategories %}
        <li>
            <a href="{{ path('category_show', {id: subcategory.id}) }}">
                {{ subcategory.name }}
            </a>
        </li>

        {% endfor %}

    </ul>

    <div class="card-deck product">
        {%  for product in category.products %}
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="//placehold.it/300x200" alt="{{ product.title }}">
            <div class="card-body">
                <h5 class="card-title">
                <a href="{{ path('product_show', {id: product.id} )}}">
                    {{ product.title }}
                </a>
                </h5>
                <p class="card-text">{{ product.price }}</p>
                <p class="card-text">{{ product.price }}</p>
            </div>
        </div>
        {% endfor %}

    </div>
{% endblock %}

{% block title %}
    {{ category.name }}
{% endblock %}